{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: connect ETIMEDOUT 159.89.8.31:3000",
  "reason": {
    "message": "connect ETIMEDOUT 159.89.8.31:3000",
    "name": "Error",
    "stack": "Error: connect ETIMEDOUT 159.89.8.31:3000\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)",
    "config": {
      "url": "http://159.89.8.31:3000",
      "method": "post",
      "data": "{\"jsonrpc\":\"2.0\",\"method\":\"getBestBlockHash\",\"params\":{},\"id\":1}",
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json;charset=utf-8",
        "User-Agent": "axios/0.19.2",
        "Content-Length": 64
      },
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 20000,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1
    },
    "code": "ETIMEDOUT"
  },
  "promise": {},
  "stack": [
    "Runtime.UnhandledPromiseRejection: Error: connect ETIMEDOUT 159.89.8.31:3000",
    "    at process.on (/var/runtime/index.js:37:15)",
    "    at process.emit (events.js:198:13)",
    "    at process.EventEmitter.emit (domain.js:448:20)",
    "    at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)",
    "    at process._tickCallback (internal/process/next_tick.js:69:34)"
  ]
}